### ISSUE TITLE
[Task] client - post detail page - cardpost

### ISSUE THREAD

**Issue by wktaylorla** [codestates/TinyHoneyTip#43]
### ISSUE
- Group: client
- Type: feature
- Detail: feature post detail page

###TODO
- [x] layout (header, footer 포함)
- [x] css(반응형)
- [x] post 이미지 부분( 좋아요, 싫어요, 스크랩 버튼)
- [x] post 이미지 부분(카드 게시물)
- [x] post 이미지 부분(현재 페이지 표시)
- [x] 서버에서 정보받아와서 표시하기

### Estimated time
> Pick one

`4h`

### Labels
- Estimated time: `E: 4h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
