### ISSUE TITLE
[Task] client - post detail page - comment

### ISSUE THREAD

**Issue by wktaylorla** [codestates/TinyHoneyTip#45]
### ISSUE
- Group: client
- Type: feature
- Detail: feature post detail page

###TODO
- [x] layout (header, footer 포함)
- [x] css(반응형)
- [x] 댓글창 (댓글 입력 부분)
- [x] 댓글창 (댓글 조회 부분)
- [x] 댓글창 (프로필)
- [x] 댓글창 (본인이 작성한 댓글 삭제 부분)
- [x] 서버에서 정보받아와서 표시하기
- [x] 서버에 request하기

### Estimated time
> Pick one

`4h`

### Labels
- Estimated time: `E: 4h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
