### ISSUE TITLE
[Task] client - post detail page - full

### ISSUE THREAD

**Issue by wktaylorla** [codestates/TinyHoneyTip#48]
### ISSUE
- Group: client
- Type: feature
- Detail: feature post detail page

###TODO
- [x] layout (header, footer, comment, cardpost)
- [x] css(반응형)
- [x] 게시물 수정 버튼
- [x] 게시물 삭제 버튼
- [x] 서버에서 정보받아와서 표시하기

### Estimated time
> Pick one

`4h`

### Labels
- Estimated time: `E: 4h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
