### ISSUE TITLE
[Task] server - mypage api

### ISSUE THREAD

**Issue by peb4010** [codestates/TinyHoneyTip#66]
### ISSUE
- Group: server
- Type: feature
- Detail: my page

###TODO
- [ ] get user information
- [ ] get my post
- [ ] get my scrap

### Estimated time
> `3h`

### Labels
- Estimated time: `E: 3h`
- Group :  `server`
- Sprint: `Sprint__NUMBER__`
- Urgency: `Middle`
